<?php
echo _("Username");
echo _("Password");
echo _("LogIn");
echo _("or");
echo _("Register");
echo _("Incorrect data");
echo _("The only thing you need to start, what are you waiting for getting one?");
echo _("Get a Posit ID");
echo _("Choose your username");
echo _("Think a safe password");
echo _("Write your e-mail address");
echo _("Get my ID");
echo _("Friends");
echo _("Notifications");
echo _("Search");
echo _("New note");
echo _("New picture");
echo _("LogOut");
echo _("You've not set up your profile yet.");
echo _("Set up profile");
echo _("Worse than a poop");
echo _("Fluffy");
echo _("Follow");
echo _("Send");
echo _("New note");
echo _("New pic");
echo _("Caption");
echo _("Picture url");
echo _("Note sent");
echo _("Picture sent");
echo _("Close");
echo _("matches");
echo _("One of the best pics this month");
echo _("One of the best posts this month");
echo _("You voted");
?>